#!/bin/bash

show_menu_kali(){
	NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}**********************************************************${NORMAL}"
    echo -e "-------------Kali Linux OS 安装中--------------"
    echo -e "\t\tConvert Lite V1.0"
    echo -e "${MENU}*********************************************************${NORMAL}"
    install
    
function include(){
	echo -e "deb https://mirrors.ustc.edu.cn/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
	apt-get update && apt-get upgrade --allow-unauthenticated -y && apt-get dist-upgrade -y  --allow-unauthenticated
}

function install(){
    include
	apt-get -f install kali-linux-full -y --allow-unauthenticated
	apt-get install linux-headers-4.14.0-kali3-amd64 -y -y
    clear
	echo -e "\n\n 安装完成!!!"
    chmod +x ./files/vnc
    ./files/vnc
    break
}
show_menu_kali
