#!/bin/bash

show_menu_parrot(){
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "-------------Parrot Linux OS 安装--------------"

    echo -e "\t\tConverto V2.O"
    echo -e "${MENU}**${NUMBER} 1)${MENU} 只安装核心 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 2)${MENU} 安装无图形界面版 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 3)${MENU} 安装标准版 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 4)${MENU} 安装完整版 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 5)${MENU} 安装家庭版 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 6)${MENU} 安装嵌入版 ${NORMAL}"
    echo -e "${MENU}*********************************************${NORMAL}"
    COUNTER=0
    while [  $COUNTER -lt 4 ]; do
        echo -e "\n${ENTER_LINE}请输入菜单选项或 ${RED_TEXT}输入7退出. ${NORMAL}"
        read -p '输入你的选择: ' i
        if (($i <7 )) && (( $i >= 1 )); then 
            install $i
            break
        elif (($i == 7 )); then
            echo -e "\nOperation terminated"
            break
        else
	    	echo -e "\n错误的选项，请重试. 错误$((3-$COUNTER)) 次后退出..)"

        fi
        let COUNTER=COUNTER+1 
    done
}
function include() {
    echo -e "deb https://mirrors.ustc.edu.cn/parrot parrot main contrib non-free" > /etc/apt/sources.list.d/parrot.list
    wget -qO - https://archive.parrotsec.org/parrot/misc/parrotsec.gpg | apt-key add -
    apt-get update
    apt-get -y --force-yes -o Dpkg::Options::="--force-overwrite" install apt-parrot parrot-archive-keyring --no-install-recommends
	apt-get update
    apt-get -y --force-yes -o Dpkg::Options::="--force-overwrite" install parrot-core
    apt-get -y --force-yes -o Dpkg::Options::="--force-overwrite" dist-upgrade
    apt-get -y --force-yes -o Dpkg::Options::="--force-overwrite" autoremove
}
function install(){
    include
    parrot=("parrot-pico" "parrot-interface parrot-tools" "parrot-interface parrot-interface-full parrot-tools-full" "parrot-interface-full parrot-interface" "parrot-interface parrot-mini")
    apt-get -y --force-yes -o Dpkg::Options::="--force-overwrite" install  $parrot[$1-1]
    echo -e "\n\n 安装成功!!!"
    echo -e "\n\n你想安装 RDP或 VNC(图形/非图形)"
    echo -e "1. 远程桌面协议(RDP)"
    echo -e "2. 虚拟网络计算(VNC)"
    echo -e "3. 都不安装"
    COUNTER=0
    while [  $COUNTER -lt 4 ]; do
        read i
        if (($i ==1 )); then
            chmod +x ./files/rdp
            ./files/rdp
            break
        elif (($i ==2 )); then
            chmod +x ./files/vnc
            ./files/vnc
            break
        elif (($i ==3 )); then
            echo "最后祝你身体健康，再见！"
            break
        else
	    	echo -e "\n错误的选项，请重试. 错误$((3-$COUNTER)) 次后退出..)"
            fi
        let COUNTER=COUNTER+1
done
}
show_menu_parrot
