#!/bin/bash
apt-get update && sudo apt-get upgrade
echo -e "\n你想安装VNC?"
echo -e "\n1. 是的， 安装VNC (图形化)"
echo "2. 是的， 安装VNC (非图形化)"
echo "3. 不，不安装VNC"
while :
do
  read INPUT_STRING
  case $INPUT_STRING in
	1)
		sudo apt-get update -y
		sudo apt-get install xfce4 xfce4-goodies tightvncserver -y --allow-unauthenticated
		vncserver
		vncserver -kill :1
		mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
		echo "#!/bin/bash
		xrdb $HOME/.Xresources
		startxfce4 &" >> ~/.vnc/xstartup
		sudo chmod +x ~/.vnc/xstartup
		echo "#!/bin/bash
		PATH="$PATH:/usr/bin/"
		export USER="user"
		DISPLAY="1"
		DEPTH="16"
		GEOMETRY="1024x768"
		OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY} -localhost"
		. /lib/lsb/init-functions" >> /etc/init.d/vncserver
		sudo chmod +x /etc/init.d/vncserver
		rm /etc/hostname
		echo "Parrot OS" >> /etc/hostname
		vncserver
		su
		clear
		echo "VNC已开启，端口 :1"
		echo "链接它!!! 例如 :- 192.168.1.1:1 "
		break
		;;
	2)	
		sudo apt-get install -y tightvncserver --allow-unauthenticated
		vncserver
		netstat -plant
		vncserver -kill :1
		vncserver
		rm /etc/hostname
		echo "Parrot OS" >> /etc/hostname
		vncserver
		su
		clear
		echo "VNC已开启，端口 :1"
		echo "链接它!!! 例如 :- 192.168.1.1:1"
		break
		;;
	3)
		echo "最后祝你身体健康，再见！"
		break
		;;
 esac
done
